on: workflow_dispatch
name: AzureARMDeploymentforBaseNetworkingandERGW
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SECONDARY }}
        enable-AzPSSession: true
        
    - name: Run ARM deploy for Base Network
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG_SHAREDNETWORK }}
        template: ./01-BaseNetworkSetup/Templates/HubNSpokeNetworksTemplate.json
        parameters: ./01-BaseNetworkSetup/Templates/HubNSpokeNetworksParameters.json

      # Deploy ARM template
    - name: Run ARM deploy for Express Route Gateway
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG_SHAREDNETWORK }}
        template: ./02-ExpressRoute/Templates/expressrouteDeployment.json
        parameters: ./02-ExpressRoute/Templates/expressrouteDeploymentParameters.json


    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
          inlineScript: 
            .\02-ExpressRoute\Scripts\CreateERCircuitConnection.ps1
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest 

      # output containerName variable from template
    # - run: echo ${{ steps.deploy.outputs.containerName }}
