on: workflow_dispatch
name: AzureARMDeploymentforVGWandRouteServer
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SECONDARY }}
        enable-AzPSSession: true
        
    - name: Run ARM deploy for Vnet Gateway & Local Network Gateway
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG_SHAREDNETWORK }}
        template: ./03-InterBranchRouting/Templates/VirturalNetworkGatewayTemplate.json
        parameters: ./03-InterBranchRouting/Templates/VirturalNetworkGatewayParameters.json

     
